-- Oracle 21c bootstrap (local demo schema)
-- Purpose: create a simple "Fusion-like" demo user + tables used by this UI templates.
--
-- Run this in your PDB as a privileged user (SYSTEM is fine).
-- Example (adjust service):
--   cd c:\path\to\oraclefusion_to_databricks
--   sqlplus system@localhost:1521/ORCLPDB1
-- Then:
--   @backend/sql/bootstrap_oracle_21c.sql

-- 1) Create demo user
BEGIN
  EXECUTE IMMEDIATE 'CREATE USER FUSION_USER IDENTIFIED BY "FusionPass123"';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO FUSION_USER';
  EXECUTE IMMEDIATE 'ALTER USER FUSION_USER QUOTA UNLIMITED ON USERS';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

-- 2) Create tables (minimal columns + LAST_UPDATE_DATE)
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE FUSION_USER.GL_JE_HEADERS (
      JE_HEADER_ID NUMBER PRIMARY KEY,
      LEDGER_ID NUMBER,
      JOURNAL_NAME VARCHAR2(200),
      JOURNAL_DATE DATE,
      LAST_UPDATE_DATE DATE
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE FUSION_USER.AP_INVOICES_ALL (
      INVOICE_ID NUMBER PRIMARY KEY,
      INVOICE_NUM VARCHAR2(50),
      SUPPLIER_NAME VARCHAR2(200),
      INVOICE_DATE DATE,
      INVOICE_AMOUNT NUMBER(18,2),
      CURRENCY_CODE VARCHAR2(10),
      LAST_UPDATE_DATE DATE
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE FUSION_USER.OE_ORDER_HEADERS_ALL (
      HEADER_ID NUMBER PRIMARY KEY,
      ORDER_NUMBER VARCHAR2(50),
      ORDER_DATE DATE,
      CUSTOMER_NAME VARCHAR2(200),
      LAST_UPDATE_DATE DATE
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 3) Seed a little data
DECLARE
  d DATE := DATE '2026-01-01';
BEGIN
  FOR i IN 1..50 LOOP
    INSERT INTO FUSION_USER.GL_JE_HEADERS (JE_HEADER_ID, LEDGER_ID, JOURNAL_NAME, JOURNAL_DATE, LAST_UPDATE_DATE)
    VALUES (i, MOD(i, 5) + 1, 'JOURNAL-' || TO_CHAR(i), d + MOD(i, 28), d + MOD(i, 28));
  END LOOP;

  FOR i IN 1..50 LOOP
    INSERT INTO FUSION_USER.AP_INVOICES_ALL (INVOICE_ID, INVOICE_NUM, SUPPLIER_NAME, INVOICE_DATE, INVOICE_AMOUNT, CURRENCY_CODE, LAST_UPDATE_DATE)
    VALUES (i, 'INV-' || TO_CHAR(i, 'FM000000'), 'Supplier ' || TO_CHAR(MOD(i, 10) + 1), d + MOD(i, 28), (MOD(i, 97) * 113.25), 'USD', d + MOD(i, 28));
  END LOOP;

  FOR i IN 1..50 LOOP
    INSERT INTO FUSION_USER.OE_ORDER_HEADERS_ALL (HEADER_ID, ORDER_NUMBER, ORDER_DATE, CUSTOMER_NAME, LAST_UPDATE_DATE)
    VALUES (i, 'SO-' || TO_CHAR(i, 'FM000000'), d + MOD(i, 28), 'Customer ' || TO_CHAR(MOD(i, 12) + 1), d + MOD(i, 28));
  END LOOP;

  COMMIT;
END;
/

PROMPT Done. User=FUSION_USER Password=FusionPass123
