import type { SimulationStep, PipelineType, ExecutionSummary } from '../types/pipeline';

export const SIMULATIONS: Record<PipelineType, SimulationStep[]> = {
  bicc: [
    { delayMs: 400, updateNodeType: 'oracle-fusion', nodeStatus: 'running', progress: 2, log: { level: 'info', message: '[CONNECT] Connecting to Oracle Fusion source (Oracle 21c @ localhost:1521)...' } },
    { delayMs: 700, progress: 5, log: { level: 'info', message: '  Driver: oracle.jdbc.OracleDriver (cx_Oracle 8.3.0)' } },
    { delayMs: 700, progress: 8, log: { level: 'success', message: '  Connected. Service: ORCLPDB1 | User: FUSION_USER | NLS: UTF8' } },
    { delayMs: 500, updateNodeType: 'oracle-fusion', nodeStatus: 'success', progress: 12, log: { level: 'info', message: '[INFO]    Source table validated: GL_JE_HEADERS (42 columns, 1,250 rows)' } },
    { delayMs: 600, updateNodeType: 'bicc', nodeStatus: 'running', progress: 15, log: { level: 'info', message: '[INIT]    BICC Export Job initiated - Full Export mode (CSV)' } },
    { delayMs: 700, progress: 20, log: { level: 'info', message: '  Format: CSV with header row' } },
    { delayMs: 600, progress: 25, log: { level: 'info', message: '  Extracting GL_JE_HEADERS WHERE LAST_UPDATE_DATE >= 2026-01-01...' } },
    { delayMs: 800, progress: 35, log: { level: 'info', message: '  Processed 500 / 1,250 rows (40%)...' } },
    { delayMs: 700, progress: 45, log: { level: 'info', message: '  Processed 1,000 / 1,250 rows (80%)...' } },
    { delayMs: 600, progress: 55, log: { level: 'success', message: '  BICC export complete: 1,250 rows -> gl_je_headers_20260311.csv (4.2 MB)' } },
    { delayMs: 400, updateNodeType: 'bicc', nodeStatus: 'success', progress: 58, log: { level: 'info', message: '[UPLOAD]  Uploading to Azure Data Lake Storage Gen2...' } },
    { delayMs: 500, updateNodeType: 'cloud-storage', nodeStatus: 'running', progress: 62, log: { level: 'info', message: '  Container: oracle-data | Path: /oracle/exports/20260311/' } },
    { delayMs: 600, progress: 68, log: { level: 'info', message: '  Uploading: gl_je_headers_20260311.csv [====================] 4.2 MB' } },
    { delayMs: 500, updateNodeType: 'cloud-storage', nodeStatus: 'success', progress: 72, log: { level: 'success', message: '  File committed: adls://oracle-data/oracle/exports/20260311/gl_je_headers_20260311.csv' } },
    { delayMs: 500, updateNodeType: 'databricks', nodeStatus: 'running', progress: 75, log: { level: 'info', message: '[START]   Databricks AutoLoader: scanning /oracle/exports/20260311/ for new files...' } },
    { delayMs: 700, progress: 80, log: { level: 'info', message: '  AutoLoader detected: gl_je_headers_20260311.csv (event: file_added)' } },
    { delayMs: 600, progress: 83, log: { level: 'info', message: '  Spark job started: autoloader_ingest_gl_je_headers [Job #47]' } },
    { delayMs: 700, progress: 87, log: { level: 'info', message: '  Reading CSV: schema inferred (42 columns). Spark partitions: 4' } },
    { delayMs: 600, progress: 92, log: { level: 'info', message: '  Writing to Delta: unity_catalog.bronze.gl_je_headers (mode: append)' } },
    { delayMs: 700, progress: 96, log: { level: 'info', message: '  OPTIMIZE applied. Z-ORDER BY journal_date, ledger_id' } },
    { delayMs: 400, updateNodeType: 'databricks', nodeStatus: 'success', progress: 100, log: { level: 'success', message: '[OK]      1,250 rows loaded to unity_catalog.bronze.gl_je_headers (Delta v14)' } },
  ],

  goldengate: [
    { delayMs: 400, updateNodeType: 'oracle-fusion', nodeStatus: 'running', progress: 2, log: { level: 'info', message: '[CONNECT] Connecting to Oracle source database (CDC mode)...' } },
    { delayMs: 700, progress: 6, log: { level: 'info', message: '  Enabling supplemental logging: ALTER DATABASE ADD SUPPLEMENTAL LOG DATA' } },
    { delayMs: 700, progress: 10, log: { level: 'success', message: '  Supplemental logging enabled. Current SCN: 4,782,341' } },
    { delayMs: 500, updateNodeType: 'oracle-fusion', nodeStatus: 'success', progress: 14, log: { level: 'info', message: '[INFO]    Oracle redo log archiving verified. Retention: 7 days' } },
    { delayMs: 600, updateNodeType: 'goldengate', nodeStatus: 'running', progress: 18, log: { level: 'info', message: '[INIT]    Oracle GoldenGate 21c: initializing Extract process (E_ORA21C)...' } },
    { delayMs: 700, progress: 23, log: { level: 'info', message: '  Install path: /opt/goldengate/21c' } },
    { delayMs: 600, progress: 28, log: { level: 'info', message: '  Extract registered with database. Reading from SCN: 4,782,341' } },
    { delayMs: 800, progress: 35, log: { level: 'info', message: '  Tailing redo logs via LogMiner. Capture started...' } },
    { delayMs: 700, progress: 42, log: { level: 'info', message: '  Trail file created: /gg/dirdat/aa000001 (processing...)' } },
    { delayMs: 600, progress: 50, log: { level: 'info', message: '  Change events captured: INSERT=612, UPDATE=198, DELETE=37' } },
    { delayMs: 700, progress: 57, log: { level: 'info', message: '  Trail file size: /gg/dirdat/aa000001 (847 records, 1.8 MB)' } },
    { delayMs: 500, progress: 63, log: { level: 'info', message: '  GoldenGate Databricks Connector: initializing JDBC endpoint...' } },
    { delayMs: 400, updateNodeType: 'goldengate', nodeStatus: 'success', progress: 67, log: { level: 'info', message: '[REPL]    Replicat process starting (R_DBX): connecting to Databricks workspace...' } },
    { delayMs: 600, updateNodeType: 'databricks', nodeStatus: 'running', progress: 72, log: { level: 'info', message: '  Target: unity_catalog.silver.orders (write mode: merge / CDC)' } },
    { delayMs: 700, progress: 78, log: { level: 'info', message: '  Applying CDC MERGE operations to Delta table...' } },
    { delayMs: 600, progress: 85, log: { level: 'success', message: '  MERGE complete: 612 INSERTed, 198 UPDATEd, 37 DELETEd' } },
    { delayMs: 500, progress: 91, log: { level: 'info', message: '  Delta log entry written. Table version: 847' } },
    { delayMs: 600, progress: 96, log: { level: 'info', message: '  CDC stream healthy. Latency: 1.2s | Trail offset: aa000001@0x00015800' } },
    { delayMs: 400, updateNodeType: 'databricks', nodeStatus: 'success', progress: 100, log: { level: 'success', message: '[OK]      847 CDC events applied to unity_catalog.silver.orders (Delta v847)' } },
  ],

  'rest-api': [
    { delayMs: 400, updateNodeType: 'oracle-fusion', nodeStatus: 'running', progress: 2, log: { level: 'info', message: '[START]   Initializing mock Oracle Fusion REST API server (FastAPI)...' } },
    { delayMs: 700, progress: 6, log: { level: 'info', message: '  Server starting at http://localhost:9000/fscmRestApi' } },
    { delayMs: 600, progress: 10, log: { level: 'success', message: '  Mock server ready. Routes: /invoices, /suppliers, /purchaseOrders' } },
    { delayMs: 500, updateNodeType: 'oracle-fusion', nodeStatus: 'success', progress: 14, log: { level: 'info', message: '[AUTH]    Acquiring OAuth2 Bearer token from identity provider...' } },
    { delayMs: 600, updateNodeType: 'rest-api', nodeStatus: 'running', progress: 18, log: { level: 'success', message: '  Token acquired (expires: 3600s). Scope: FscmRestApi.all' } },
    { delayMs: 700, progress: 25, log: { level: 'info', message: '[GET]     /fscmRestApi/resources/11.13.18.05/invoices?limit=200&offset=0&lastUpdateDate=2026-01-01' } },
    { delayMs: 600, progress: 35, log: { level: 'info', message: '  Page 1/5 received: 200 records (HTTP 200 OK, 1.24s)' } },
    { delayMs: 500, progress: 44, log: { level: 'info', message: '  Page 2/5 received: 200 records (HTTP 200 OK, 0.98s)' } },
    { delayMs: 500, progress: 53, log: { level: 'info', message: '  Page 3/5 received: 200 records (HTTP 200 OK, 1.02s)' } },
    { delayMs: 500, progress: 62, log: { level: 'info', message: '  Page 4/5 received: 200 records (HTTP 200 OK, 0.87s)' } },
    { delayMs: 500, progress: 70, log: { level: 'success', message: '  Page 5/5 received: 200 records. Total: 1,000 records fetched via paginated REST' } },
    { delayMs: 400, updateNodeType: 'rest-api', nodeStatus: 'success', progress: 73, log: { level: 'info', message: '[XFORM]   Transforming JSON payload to Spark DataFrame schema...' } },
    { delayMs: 600, updateNodeType: 'databricks', nodeStatus: 'running', progress: 78, log: { level: 'info', message: '  Schema: 28 fields detected, 3 nested objects flattened' } },
    { delayMs: 700, progress: 84, log: { level: 'info', message: '  Writing to Delta: unity_catalog.bronze.invoices_api (mode: append)' } },
    { delayMs: 600, progress: 91, log: { level: 'info', message: '  Commit complete. Delta table version: 23. File count: 4' } },
    { delayMs: 400, updateNodeType: 'databricks', nodeStatus: 'success', progress: 100, log: { level: 'success', message: '[OK]      1,000 rows loaded to unity_catalog.bronze.invoices_api (Delta v23)' } },
  ],

  jdbc: [
    { delayMs: 400, updateNodeType: 'oracle-fusion', nodeStatus: 'running', progress: 2, log: { level: 'info', message: '[START]   Initializing Apache Spark session (local[*] mode)...' } },
    { delayMs: 700, progress: 6, log: { level: 'info', message: '  Spark UI: http://localhost:4040 | Version: 3.5.0' } },
    { delayMs: 600, progress: 10, log: { level: 'success', message: '  Spark session ready. Executor memory: 4g | Cores: 8' } },
    { delayMs: 500, updateNodeType: 'oracle-fusion', nodeStatus: 'success', progress: 14, log: { level: 'info', message: '[CONNECT] JDBC connection: jdbc:oracle:thin:@localhost:1521/ORCLPDB1' } },
    { delayMs: 600, updateNodeType: 'jdbc', nodeStatus: 'running', progress: 18, log: { level: 'success', message: '  Authentication: FUSION_USER | Driver: oracle.jdbc.OracleDriver (21.12)' } },
    { delayMs: 700, progress: 24, log: { level: 'info', message: "[QUERY]   SELECT * FROM AP_INVOICES_ALL WHERE LAST_UPDATE_DATE > '2026-01-01'" } },
    { delayMs: 600, progress: 30, log: { level: 'info', message: '  Pushdown filter applied - Oracle executes filter natively' } },
    { delayMs: 800, progress: 38, log: { level: 'info', message: '  Fetching with 10 parallel partitions (column: INVOICE_ID, stride: 245)' } },
    { delayMs: 700, progress: 47, log: { level: 'info', message: '  Partitions 1-5 complete: 1,225 rows...' } },
    { delayMs: 700, progress: 57, log: { level: 'info', message: '  Partitions 6-10 complete: 1,225 rows...' } },
    { delayMs: 500, progress: 63, log: { level: 'success', message: '  JDBC read complete: 2,450 rows fetched (87 columns)' } },
    { delayMs: 400, updateNodeType: 'jdbc', nodeStatus: 'success', progress: 66, log: { level: 'info', message: '[XFORM]   Applying schema mapping and data type casting...' } },
    { delayMs: 600, updateNodeType: 'databricks', nodeStatus: 'running', progress: 72, log: { level: 'info', message: '  Null handling: 3 nullable columns coalesced' } },
    { delayMs: 700, progress: 79, log: { level: 'info', message: '  Writing to Delta: unity_catalog.bronze.ap_invoices_jdbc (mode: append)' } },
    { delayMs: 700, progress: 87, log: { level: 'info', message: '  Running OPTIMIZE on table...' } },
    { delayMs: 600, progress: 94, log: { level: 'info', message: '  Z-ORDER BY invoice_date, supplier_id applied (3.2s)' } },
    { delayMs: 400, updateNodeType: 'databricks', nodeStatus: 'success', progress: 100, log: { level: 'success', message: '[OK]      2,450 rows loaded to unity_catalog.bronze.ap_invoices_jdbc (Delta v12)' } },
  ],

  custom: [
    { delayMs: 400, updateNodeType: 'oracle-fusion', nodeStatus: 'running', progress: 5, log: { level: 'info', message: '[CONNECT] Connecting to Oracle Fusion source...' } },
    { delayMs: 1000, updateNodeType: 'oracle-fusion', nodeStatus: 'success', progress: 20, log: { level: 'success', message: '[OK]      Oracle Fusion connected. Source validated.' } },
    { delayMs: 800, progress: 50, log: { level: 'info', message: '[PROCESS] Processing data pipeline...' } },
    { delayMs: 1200, updateNodeType: 'databricks', nodeStatus: 'running', progress: 70, log: { level: 'info', message: '[START]   Writing to Databricks Unity Catalog...' } },
    { delayMs: 1000, updateNodeType: 'databricks', nodeStatus: 'success', progress: 100, log: { level: 'success', message: '[OK]      Pipeline execution complete.' } },
  ],
};

export const EXECUTION_SUMMARIES: Record<PipelineType, ExecutionSummary> = {
  bicc: { rowsExtracted: 1250, rowsLoaded: 1250, timeTakenMs: 10600, pipelineType: 'bicc' },
  goldengate: { rowsExtracted: 847, rowsLoaded: 847, timeTakenMs: 9400, pipelineType: 'goldengate' },
  'rest-api': { rowsExtracted: 1000, rowsLoaded: 1000, timeTakenMs: 7600, pipelineType: 'rest-api' },
  jdbc: { rowsExtracted: 2450, rowsLoaded: 2450, timeTakenMs: 8200, pipelineType: 'jdbc' },
  custom: { rowsExtracted: 500, rowsLoaded: 500, timeTakenMs: 4400, pipelineType: 'custom' },
};
